In [ ]:
! pip install transformers datasets torch
! pip install --upgrade tensorflow_hub
! pip install evaluate

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from datasets import Dataset, load_dataset
import torch
import tensorflow_hub as hub

WARNING:tensorflow:From c:\Users\Yohan\anaconda3\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [ ]:
# import dataset
dataset = pd.read_csv('../dataset/cleaned_dataset_bert.csv')
dataset.shape

(51093, 2)

In [4]:
dataset.head()

                                      processed_text   status
0                                         oh my gosh  Anxiety
1  trouble sleeping confused mind restless heart ...  Anxiety
2  all wrong back off dear forward doubt stay in ...  Anxiety
3  i have shifted my focus to something else but ...  Anxiety
4  i am restless and restless it is been a month ...  Anxiety

In [5]:
dataset['status'].value_counts()

status
Normal                  16040
Depression              15094
Suicidal                10644
Anxiety                  3623
Bipolar                  2501
Stress                   2296
Personality disorder      895
Name: count, dtype: int64

In [6]:
# label encoding
unique_labels = sorted(dataset['status'].unique())
unique_labels

['Anxiety',
 'Bipolar',
 'Depression',
 'Normal',
 'Personality disorder',
 'Stress',
 'Suicidal']

In [7]:
label_to_id = {label: i for i, label in enumerate(unique_labels)}
id_to_label = {i: label for label, i in label_to_id.items()}

dataset['label'] = dataset['status'].map(label_to_id)
print(f"Unique Classes: {unique_labels}")
print(f"Label Mapping: {label_to_id}")
print("-" * 40)

dataset.head()

Unique Classes: ['Anxiety', 'Bipolar', 'Depression', 'Normal', 'Personality disorder', 'Stress', 'Suicidal']
Label Mapping: {'Anxiety': 0, 'Bipolar': 1, 'Depression': 2, 'Normal': 3, 'Personality disorder': 4, 'Stress': 5, 'Suicidal': 6}
----------------------------------------

                                      processed_text   status  label
0                                         oh my gosh  Anxiety      0
1  trouble sleeping confused mind restless heart ...  Anxiety      0
2  all wrong back off dear forward doubt stay in ...  Anxiety      0
3  i have shifted my focus to something else but ...  Anxiety      0
4  i am restless and restless it is been a month ...  Anxiety      0

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    dataset['processed_text'],
    dataset['label'],
    stratify=dataset['label']
)

In [9]:
%pip install torch==2.1.0 torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118
%pip install transformers==4.36.2
%pip install datasets==2.15.0
%pip install accelerate==0.25.0

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement torch==2.1.0 (from versions: 2.2.0, 2.2.0+cu118, 2.2.1, 2.2.1+cu118, 2.2.2, 2.2.2+cu118, 2.3.0, 2.3.0+cu118, 2.3.1, 2.3.1+cu118, 2.4.0, 2.4.0+cu118, 2.4.1, 2.4.1+cu118, 2.5.0, 2.5.0+cu118, 2.5.1, 2.5.1+cu118, 2.6.0, 2.6.0+cu118, 2.7.0, 2.7.0+cu118, 2.7.1, 2.7.1+cu118, 2.8.0, 2.9.0, 2.9.1)
ERROR: No matching distribution found for torch==2.1.0

Requirement already satisfied: transformers==4.36.2 in c:\users\yohan\anaconda3\lib\site-packages (4.36.2)
Requirement already satisfied: filelock in c:\users\yohan\anaconda3\lib\site-packages (from transformers==4.36.2) (3.13.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in c:\users\yohan\anaconda3\lib\site-packages (from transformers==4.36.2) (0.34.3)
Requirement already satisfied: numpy>=1.17 in c:\users\yohan\anaconda3\lib\site-packages (from transformers==4.36.2) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\yohan\anaconda3\lib\site-packages (from transformers==4.36.2) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\yohan\anaconda3\lib\site-packages (from transformers==4.36.2) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in c:\users\yohan\anaconda3\lib\site-packages (from transformers==4.36.2) (2024.9.11)
Requirement already satisfied: requests in c:\users\yohan\anaconda3\lib\site-packages (from transformers==4.36.2) (2.32.3)
Requirement already satisfied: tokenizers<0.19,>=0.14 in c:\users\yohan\anaconda3\lib\site-packages (from transformers==4.36.2) (0.15.2)
Requirement already satisfied: safetensors>=0.3.1 in c:\users\yohan\anaconda3\lib\site-packages (from transformers==4.36.2) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in c:\users\yohan\anaconda3\lib\site-packages (from transformers==4.36.2) (4.66.5)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\yohan\anaconda3\lib\site-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.36.2) (2023.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\yohan\anaconda3\lib\site-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.36.2) (4.15.0)
Requirement already satisfied: colorama in c:\users\yohan\anaconda3\lib\site-packages (from tqdm>=4.27->transformers==4.36.2) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\yohan\anaconda3\lib\site-packages (from requests->transformers==4.36.2) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\yohan\anaconda3\lib\site-packages (from requests->transformers==4.36.2) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\yohan\anaconda3\lib\site-packages (from requests->transformers==4.36.2) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\yohan\anaconda3\lib\site-packages (from requests->transformers==4.36.2) (2025.1.31)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: datasets==2.15.0 in c:\users\yohan\anaconda3\lib\site-packages (2.15.0)
Requirement already satisfied: numpy>=1.17 in c:\users\yohan\anaconda3\lib\site-packages (from datasets==2.15.0) (1.26.4)
Requirement already satisfied: pyarrow>=8.0.0 in c:\users\yohan\anaconda3\lib\site-packages (from datasets==2.15.0) (16.1.0)
Requirement already satisfied: pyarrow-hotfix in c:\users\yohan\anaconda3\lib\site-packages (from datasets==2.15.0) (0.7)
Requirement already satisfied: dill<0.3.8,>=0.3.0 in c:\users\yohan\anaconda3\lib\site-packages (from datasets==2.15.0) (0.3.7)
Requirement already satisfied: pandas in c:\users\yohan\anaconda3\lib\site-packages (from datasets==2.15.0) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in c:\users\yohan\anaconda3\lib\site-packages (from datasets==2.15.0) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in c:\users\yohan\anaconda3\lib\site-packages (from datasets==2.15.0) (4.66.5)
Requirement already satisfied: xxhash in c:\users\yohan\anaconda3\lib\site-packages (from datasets==2.15.0) (3.5.0)
Requirement already satisfied: multiprocess in c:\users\yohan\anaconda3\lib\site-packages (from datasets==2.15.0) (0.70.15)
Requirement already satisfied: fsspec<=2023.10.0,>=2023.1.0 in c:\users\yohan\anaconda3\lib\site-packages (from fsspec[http]<=2023.10.0,>=2023.1.0->datasets==2.15.0) (2023.10.0)
Requirement already satisfied: aiohttp in c:\users\yohan\anaconda3\lib\site-packages (from datasets==2.15.0) (3.10.5)
Requirement already satisfied: huggingface-hub>=0.18.0 in c:\users\yohan\anaconda3\lib\site-packages (from datasets==2.15.0) (0.34.3)
Requirement already satisfied: packaging in c:\users\yohan\anaconda3\lib\site-packages (from datasets==2.15.0) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\yohan\anaconda3\lib\site-packages (from datasets==2.15.0) (6.0.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\yohan\anaconda3\lib\site-packages (from aiohttp->datasets==2.15.0) (2.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\yohan\anaconda3\lib\site-packages (from aiohttp->datasets==2.15.0) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\yohan\anaconda3\lib\site-packages (from aiohttp->datasets==2.15.0) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\yohan\anaconda3\lib\site-packages (from aiohttp->datasets==2.15.0) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\yohan\anaconda3\lib\site-packages (from aiohttp->datasets==2.15.0) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\yohan\anaconda3\lib\site-packages (from aiohttp->datasets==2.15.0) (1.11.0)
Requirement already satisfied: filelock in c:\users\yohan\anaconda3\lib\site-packages (from huggingface-hub>=0.18.0->datasets==2.15.0) (3.13.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\yohan\anaconda3\lib\site-packages (from huggingface-hub>=0.18.0->datasets==2.15.0) (4.15.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\yohan\anaconda3\lib\site-packages (from requests>=2.19.0->datasets==2.15.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\yohan\anaconda3\lib\site-packages (from requests>=2.19.0->datasets==2.15.0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\yohan\anaconda3\lib\site-packages (from requests>=2.19.0->datasets==2.15.0) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\yohan\anaconda3\lib\site-packages (from requests>=2.19.0->datasets==2.15.0) (2025.1.31)
Requirement already satisfied: colorama in c:\users\yohan\anaconda3\lib\site-packages (from tqdm>=4.62.1->datasets==2.15.0) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yohan\anaconda3\lib\site-packages (from pandas->datasets==2.15.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\yohan\anaconda3\lib\site-packages (from pandas->datasets==2.15.0) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\yohan\anaconda3\lib\site-packages (from pandas->datasets==2.15.0) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\yohan\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets==2.15.0) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: accelerate==0.25.0 in c:\users\yohan\anaconda3\lib\site-packages (0.25.0)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.17 in c:\users\yohan\anaconda3\lib\site-packages (from accelerate==0.25.0) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\yohan\anaconda3\lib\site-packages (from accelerate==0.25.0) (24.1)
Requirement already satisfied: psutil in c:\users\yohan\anaconda3\lib\site-packages (from accelerate==0.25.0) (5.9.0)
Requirement already satisfied: pyyaml in c:\users\yohan\anaconda3\lib\site-packages (from accelerate==0.25.0) (6.0.1)
Requirement already satisfied: torch>=1.10.0 in c:\users\yohan\anaconda3\lib\site-packages (from accelerate==0.25.0) (2.7.1)
Requirement already satisfied: huggingface-hub in c:\users\yohan\anaconda3\lib\site-packages (from accelerate==0.25.0) (0.34.3)
Requirement already satisfied: safetensors>=0.3.1 in c:\users\yohan\anaconda3\lib\site-packages (from accelerate==0.25.0) (0.5.3)
Requirement already satisfied: filelock in c:\users\yohan\anaconda3\lib\site-packages (from torch>=1.10.0->accelerate==0.25.0) (3.13.1)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\yohan\anaconda3\lib\site-packages (from torch>=1.10.0->accelerate==0.25.0) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\yohan\anaconda3\lib\site-packages (from torch>=1.10.0->accelerate==0.25.0) (1.14.0)
Requirement already satisfied: networkx in c:\users\yohan\anaconda3\lib\site-packages (from torch>=1.10.0->accelerate==0.25.0) (3.3)
Requirement already satisfied: jinja2 in c:\users\yohan\anaconda3\lib\site-packages (from torch>=1.10.0->accelerate==0.25.0) (3.1.4)
Requirement already satisfied: fsspec in c:\users\yohan\anaconda3\lib\site-packages (from torch>=1.10.0->accelerate==0.25.0) (2023.10.0)
Requirement already satisfied: setuptools in c:\users\yohan\anaconda3\lib\site-packages (from torch>=1.10.0->accelerate==0.25.0) (75.1.0)
Requirement already satisfied: requests in c:\users\yohan\anaconda3\lib\site-packages (from huggingface-hub->accelerate==0.25.0) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\yohan\anaconda3\lib\site-packages (from huggingface-hub->accelerate==0.25.0) (4.66.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\yohan\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=1.10.0->accelerate==0.25.0) (1.3.0)
Requirement already satisfied: colorama in c:\users\yohan\anaconda3\lib\site-packages (from tqdm>=4.42.1->huggingface-hub->accelerate==0.25.0) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\yohan\anaconda3\lib\site-packages (from jinja2->torch>=1.10.0->accelerate==0.25.0) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\yohan\anaconda3\lib\site-packages (from requests->huggingface-hub->accelerate==0.25.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\yohan\anaconda3\lib\site-packages (from requests->huggingface-hub->accelerate==0.25.0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\yohan\anaconda3\lib\site-packages (from requests->huggingface-hub->accelerate==0.25.0) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\yohan\anaconda3\lib\site-packages (from requests->huggingface-hub->accelerate==0.25.0) (2025.1.31)

In [10]:
from transformers import BertTokenizer, BertForSequenceClassification
from transformers import Trainer, TrainingArguments
import torch
from torch.utils.data import Dataset

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

c:\Users\Yohan\anaconda3\Lib\site-packages\transformers\utils\generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
c:\Users\Yohan\anaconda3\Lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
W1112 16:58:35.100000 18540 site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
c:\Users\Yohan\anaconda3\Lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
c:\Users\Yohan\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:945: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [11]:
dataset.head()

                                      processed_text   status  label
0                                         oh my gosh  Anxiety      0
1  trouble sleeping confused mind restless heart ...  Anxiety      0
2  all wrong back off dear forward doubt stay in ...  Anxiety      0
3  i have shifted my focus to something else but ...  Anxiety      0
4  i am restless and restless it is been a month ...  Anxiety      0

In [12]:
X = dataset['processed_text'].values
y = dataset['label'].values

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [19]:
text_column_name = 'processed_text'
label_column_name = "status"

#model_name = "distilbert-base-uncased"
model_name = "bert-base-uncased"
text_size = 0.2
num_labels = 7

In [15]:
df_train, df_test = train_test_split(
    dataset,
    test_size=text_size
)

In [16]:
from datasets import Dataset

In [17]:
train_dataset = Dataset.from_pandas(df_train)
test_dataset = Dataset.from_pandas(df_test)

In [20]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(model_name)

c:\Users\Yohan\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:945: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [23]:
def preprocess_function(examples):
    return tokenizer(
        examples['processed_text'],
        truncation=True,
        padding="max_length")

In [24]:
tokenizer_train = train_dataset.map(preprocess_function, batched=True)

Map:   0%|          | 0/40874 [00:00<?, ? examples/s]

TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]